github action for pages deploy
DarkRiftNetworking/DarkRift.Documentation pull request #24
Opened 2023-06-24 18:47 UTC by brettriekman

adding workflow to build the pages and publish

couple of settings required  shown below

give the token access to publish to the repo and once its made a branch select the gh-pages branch as the deploy branch in the pages setting

![](https://cdn.discordapp.com/attachments/1079323624818880543/1122235328212770826/image.png)

![](https://cdn.discordapp.com/attachments/1079323624818880543/1122236174497497160/image.png)

2023-06-25 10:52 UTC, JamJar00 requested changes

2023-06-25 10:52 UTC, JamJar00 commented on .github/workflows/pages.yaml
> +      - name: Chekout
Typo! 
```suggestion
      - name: Checkout
```

2023-06-26 20:42 UTC, JamJar00 approved these changes

2023-06-26 20:47 UTC, JamJar00 commented
New policy is for two mods to approve so will prod someone to give you another approval!

2023-07-16 17:01 UTC, MrBabadook approved these changes
Seems good - will have to update them in the future to fix Configuration not pointing at a valid URL but thanks for getting this built :)

2023-07-16 17:54 UTC, brettriekman commented
remove the on push and added workflow_dispatch so we can manually trigger instead

2024-10-19 22:54 UTC, closed without merging