Tutorial 1.1
DarkRiftNetworking/DarkRift.Documentation pull request #5
Opened 2019-10-13 09:38 UTC by Penca53

I've added some bold text and some quotes to highlight the key words.

2019-10-16 21:13 UTC, JamJar00 commented on getting_started/2_the_unity_scene.md
> +In a blank Unity scene add an empty GameObject, rename it `Network` and then add a `DarkRift -> Client` component.
Really like the addition of backticks!

2019-10-16 21:32 UTC, JamJar00 commented
Thanks for the Pull Request Penca!

I'm made quite a few comments but most of them a one character changes. I really like the addition of backticks, they make it much easier to determine what's code references! Nice work!

I would quite like to reduce the amount of bold used though, I just feel like there's so much that it detracts from the really important bold words you've added! Can I set a rough target for you to halve it? I know that's quite a lot but I think it would reduce a lot of the distraction but still really add to the clarity! 🙂 

Thanks for taking the time to edit this!

Jamie

2019-10-21 17:17 UTC, JamJar00 commented
This looks much better I think!

There's sill a few peculiarities with backticks though that would be good to sort out and then we should be there! Nice work 🙂

2019-10-22 16:32 UTC, Penca53 commented
I've removed some backticks... Tell me if there is anything else to do!

2019-10-30 19:38 UTC, JamJar00 commented
Hey Penca, sorry I've not looked at this sooner!

I'm still not convinced by this, I think you've removed some instances of backticks where they really added to the formatting!

Let me give you some examples. The first, `Kill` is a really good one to keep as it's the name of a method! Similarly, `MouseController`, `NetworkPlayer`, and `ControllablePlayer` are really good as they're prefab/gameobject /script names but you've removed some of them! Thinks like `using DarkRift;` and `using DarkRift.Server;` (in server basics) are also perfect examples of when to use backticks, they're literally code snippets!

The only instances I was concerned about were things like `PlayerSpawner component` and `Network object` where you've included both the name of a component/object and also the word after it!

It would be really good if you could revert the last commit and we'll meet in the middle there!

Thanks for the patience!

Jamie

2019-11-01 18:44 UTC, JamJar00 requested changes
This look absolutely brilliant now Penca!

I've just a few, mostly 1 character, changes now and then I'll merge!

Thanks for the hard work 🙂 

Jamie

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/3_server_basics.md
> +Go ahead and make `AgarPlayerManager` **inherit** from `Plugin`, you’ll notice Visual Studio throws an **error** saying that there is **no constructor** so **add it**. You’ll then notice it says that
I'm a little concerned about the number of bold words, I really like the use of the bold where they're really key points such as line 9: "server", "client", and "both"; but I'm not sure if a lot of those words highlighted in this paragraph need to be. It feels like when you have unecessary words like "this" highlighted it detracts from the purpose of making words bold.

Would you be able to reduce the number of words that are bold a little so that it really makes the most important stand out?

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/3_server_basics.md
> +After some **formatting**, we should have something **like**:
Another really good example, "formatting" works bold but "like" seems a bit unecessary to me :|

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/4_first_network_code.md
> +The first thing that we need to do is make **players** **appear** when someone logs in. We need to make sure that the **person logging** in receives a **list of all players** that are currently **onl
"person logging" seems wrong, did you mean to highligh "in" as well?

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/4_first_network_code.md
> +The first thing that we need to do is make **players** **appear** when someone logs in. We need to make sure that the **person logging** in receives a **list of all players** that are currently **onl
I really like the bold highlighting in the list below though actually!

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/4_first_network_code.md
> +The `ClientManager` is responsible for **keeping track** of **any clients* that are **connected** to the **server** so you can use it to **access clients** and it can inform you when clients **connec
You're missing an `*` on "any clients" so the formatting gets mixed up

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/4_first_network_code.md
> +Hopefully this should be fairly self-explanatory from what we’ve already done, the only difference is that we keep **writing** into the **same writer** so that it’s all in **one message**. Note that
You seem to be missing a closing `**` here.

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/5_movement.md
> +Now that’s done try to **fill** in the ``Player`` **class** with code to **send** our **position**. All that needs to be sent is the **x** and **y** components of `transform.position`.
Think you have too many backticks around `Player`!

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/5_movement.md
> +If you’re stuck, here’s the code I wrote **after** the **Distance if statement**:
Lower case `d` on `Distance`?

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/4_first_network_code.md
> +Let’s give our newly connected player their own `Player object`. In our `ClientConnected` method add code to generate them a **new player** setup with random values:
Are the backticks supposed to be around "object" as well? Backticks are usually used for code references so I think just around Player is probably more correct!

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/4_first_network_code.md
> +You might notice the sneaky `e.Client.ID` hiding in there. So that we can address the player when it’s on the Unity side we need to have an **identifier**, since the client will only have one `Player
Again, not sure "object" should be in the backticked section :)

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/5_movement.md
> +Now that’s done try to fill in the `Player class` with code to **send** our **position**. All that needs to be sent is the **x** and **y** components of `transform.position`.
I'd probably keep the backticks around Player, sorry!

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/5_movement.md
> +Now that’s done try to fill in the `Player class` with code to **send** our **position**. All that needs to be sent is the **x** and **y** components of `transform.position`.
There's a few other instances of this scattered around :)

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/5_movement.md
> +On our server we need to track** the positional changes of **each player** so that new players connecting always get the latest position, we also need to **send** this **movement** update message out
You have an extra set of asterisks on "track" that shouldn't be there!

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/9_omnomnomnom.md
> +Add a new C# file to our server plugin called `AgarFoodManager` and make the class a `DarkRift plugin` (first challenge!). Make sure you set `ThreadSafe` to **false** so you don’t have problems later
Can you remove the backticks around "DarkRift plugin" please?

2019-11-01 18:44 UTC, JamJar00 commented on getting_started/9_omnomnomnom.md
> +While we’re testing, add some code to set `the CameraFollow.Target` on our `Main Camera` to our player so that it follows them around.
Backtick should be after "the" 🙂

2019-11-02 09:54 UTC, Penca53 commented
I don't know why there were so many bold texts... that looked like my first commit but after you told me to remove some, I removed some bold texts... strange 😄

2019-11-04 20:11 UTC, JamJar00 commented
Awesome work! 😄

2019-11-04 20:11 UTC, merged